#!/bin/bash
git add $1
git commit -m "$2"
git push
git status
echo -e "
⊂_ヽ
　 ＼＼ ＿
　　 ＼(　•_•) F
　　　 <　⌒ヽ A
　　　/ 　 へ＼ B
　　 /　　/　＼＼ U
　　 ﾚ　ノ　　 ヽ_つ L
　　/　/ O
　 /　/ U
　(　(ヽ S
　|　|、＼.
　| 丿 ＼ ⌒)
　| |　　) /
ノ )　　Lﾉ__
(／__"
